# Parameters.
import math

# Change as desired.
DEFAULT_FIELD_WIDTH = 50
DEFAULT_FIELD_HEIGHT = 15
DEFAULT_SWARM_WIDTH = math.floor(DEFAULT_FIELD_WIDTH / 5 * 2)
DEFAULT_SWARM_HEIGHT = math.floor(DEFAULT_FIELD_HEIGHT / 3 * 2)
DEFAULT_SWARM_SIZE = 80#(DEFAULT_SWARM_WIDTH * DEFAULT_SWARM_HEIGHT) >> 3

INVADER_SYMBOL = 'A'
INVADER_BULLET_SYMBOL = 'v'
TANK_SYMBOL = 'U'
TANK_BULLET_SYMBOL = '^'
BOTH_BULLET_SYMBOL = '|'
EXPLOSION_SYMBOL = '@'
EMPTY_SYMBOL = ' '
FRAME_SYMBOL = '|'

# Enums, don't touch these!
FACTION_TANK = 0
FACTION_INVADER = 1